### ISSUE TITLE
jquery/validator missing in autofill.js

### ISSUE THREAD

**Issue by marcoveeneman** [postcode-nl/PostcodeNl_Api_Magento2#71]
Hi,

I was trying to use the postcode check on the customer change address form, but the autofill.js module failed to load.
`componentLoadingFail {component: 'Flekto_Postcode/js/view/customer/address/autofill'}` _(Using version 3.1.9)_

When stepping in the code it appears the following line:
```
validatorInstance: $('.form-address-edit').validate(),
```

Is causing this exception:
```
"TypeError: $(...).validate is not a function
    at http://127.0.0.1/static/version1671735671/frontend/Vendor/theme/nl_NL/Flekto_Postcode/js/view/customer/address/autofill.js:11:56
    at Object.execCb (http://127.0.0.1/static/version1671735671/frontend/Vendor/theme/nl_NL/requirejs/require.js:1650:33)
    at context.execCb (http://127.0.0.1/static/version1671735671/frontend/Vendor/theme/nl_NL/mage/requirejs/resolver.js:156:31)
    at Module.check (http://127.0.0.1/static/version1671735671/frontend/Vendor/theme/nl_NL/requirejs/require.js:861:55)
    at Module.enable (http://127.0.0.1/static/version1671735671/frontend/Vendor/theme/nl_NL/requirejs/require.js:1143:22)
    at Module.init (http://127.0.0.1/static/version1671735671/frontend/Vendor/theme/nl_NL/requirejs/require.js:774:26)
    at callGetModule (http://127.0.0.1/static/version1671735671/frontend/Vendor/theme/nl_NL/requirejs/require.js:1170:63)
    at Object.completeLoad (http://127.0.0.1/static/version1671735671/frontend/Vendor/theme/nl_NL/requirejs/require.js:1544:21)
    at HTMLScriptElement.onScriptLoad (http://127.0.0.1/static/version1671735671/frontend/Vendor/theme/nl_NL/requirejs/require.js:1671:29)"
```

**Potential fix**
After fiddling around a bit it seems the following change is fixing the problem for me:
in `autofill.js` change this
```js
define([
    'uiCollection',
    'uiRegistry',
    'jquery',
], function (Collection, Registry, $) {
```
to
```js
define([
    'uiCollection',
    'uiRegistry',
    'jquery',
    'jquery/validate',
], function (Collection, Registry, $) {
```

Can you confirm this problem and that this is the correct fix? Thanks!

**Comment by JerrySmidt** [comment]
Hello,

Sure, this fix looks correct to me. It makes sense to add because `autofil.js` does depend on the jQuery Validation Plugin.

I can't confirm this problem however, the jQuery validator already exists at the address edit page in my local Magento installation (version 2.4.5-p1). But for some reason it's not loaded on your side.

Thanks for reporting, I'll include the fix in the next release.
