### ISSUE TITLE
Postcode field not loading when we try to open store on new device.

### ISSUE THREAD

**Issue by kevalkavathiya** [postcode-nl/PostcodeNl_Api_Magento2#72]
![image](https://user-images.githubusercontent.com/41768026/219283759-1d327eac-4498-47a6-933a-0bbc27b2387c.png)

I used this module's latest version and I am getting issues when trying to open the checkout page very first time on the new device I think it is happening due to below errors.

![image](https://user-images.githubusercontent.com/41768026/219283683-a6edd529-d6ef-4e22-a83a-6637c8f89143.png)
![image](https://user-images.githubusercontent.com/41768026/219283640-e10ad47b-98fa-457f-843d-cdae21c8ada7.png)

After the refresh, page errors have not been generated and it is working again. If any idea about this could you please help us to resolve this?

**Comment by tausif22** [comment]
@kevalkavathiya 

I have faced same issue like this.

**Comment by Paulsky** [comment]
You could try this patch mentioned here: https://github.com/postcode-nl/PostcodeNl_Api_Magento2/issues/77#issuecomment-1495774477 . But not sure if you will expierence side affects mentioned here: https://github.com/postcode-nl/PostcodeNl_Api_Magento2/pull/78#issuecomment-1499135694

**Comment by kevalkavathiya** [comment]
I have added the changes from https://github.com/postcode-nl/PostcodeNl_Api_Magento2/pull/78 pull request and its working for me.

**Comment by Paulsky** [comment]
@kevalkavathiya great to hear! Could you please re-open this issue and keep it open...? Because it's still an issue which is not yet permanently fixed I guess....

What do you think @JerrySmidt ?

**Comment by JerrySmidt** [comment]
Still unresolved, see https://github.com/postcode-nl/PostcodeNl_Api_Magento2/pull/78#issuecomment-1499135694

**Comment by marcoveeneman** [comment]
I have seen this issue happening as well, not knowing exactly what the root cause is, and I'm afraid some customers can see the same behaviour and don't know what to do, possibly causing a cart to be abandoned. The strange thing is it is not always happening.

Setup:
- Magento 2.4.5-p4
- Postcode-nl 3.1.11

I managed to get the following console log in chrome (note there are some duplicate messages):
```ts
jquery.js:4050 jQuery.Deferred exception: Cannot read properties of undefined (reading 'show_hide_address_fields') TypeError: Cannot read properties of undefined (reading 'show_hide_address_fields')
    at UiClass.initialize (https://www.example.com/static/version1234567890/frontend/Vendor/theme-example/nl_NL/Flekto_Postcode/js/form/element/house-number-select.js:18:31)
    at UiClass.initialize (https://www.example.com/static/version1234567890/frontend/Vendor/theme-example/nl_NL/mage/utils/wrapper.js:109:34)
    at new UiClass (https://www.example.com/static/version1234567890/frontend/Vendor/theme-example/nl_NL/Magento_Ui/js/lib/core/class.js:49:32)
    at initComponent (https://www.example.com/static/version1234567890/frontend/Vendor/theme-example/nl_NL/Magento_Ui/js/core/renderer/layout.js:137:25)
    at fire (https://www.example.com/static/version1234567890/frontend/Vendor/theme-example/nl_NL/jquery.js:3500:50)
    at fireWith (https://www.example.com/static/version1234567890/frontend/Vendor/theme-example/nl_NL/jquery.js:3630:29)
    at mightThrow (https://www.example.com/static/version1234567890/frontend/Vendor/theme-example/nl_NL/jquery.js:3825:80)
    at process (https://www.example.com/static/version1234567890/frontend/Vendor/theme-example/nl_NL/jquery.js:3834:49)
    at https://www.example.com/static/version1234567890/frontend/Vendor/theme-example/nl_NL/jquery.js:3864:37
    at mightThrow (https://www.example.com/static/version1234567890/frontend/Vendor/theme-example/nl_NL/jquery.js:3766:60) undefined
jQuery.Deferred.exceptionHook @ jquery.js:4050
jquery.js:4050 jQuery.Deferred exception: Cannot read properties of undefined (reading 'show_hide_address_fields') TypeError: Cannot read properties of undefined (reading 'show_hide_address_fields')
    at UiClass.initialize (https://www.example.com/static/version1234567890/frontend/Vendor/theme-example/nl_NL/Flekto_Postcode/js/form/element/house-number-select.js:18:31)
    at UiClass.initialize (https://www.example.com/static/version1234567890/frontend/Vendor/theme-example/nl_NL/mage/utils/wrapper.js:109:34)
    at new UiClass (https://www.example.com/static/version1234567890/frontend/Vendor/theme-example/nl_NL/Magento_Ui/js/lib/core/class.js:49:32)
    at initComponent (https://www.example.com/static/version1234567890/frontend/Vendor/theme-example/nl_NL/Magento_Ui/js/core/renderer/layout.js:137:25)
    at fire (https://www.example.com/static/version1234567890/frontend/Vendor/theme-example/nl_NL/jquery.js:3500:50)
    at fireWith (https://www.example.com/static/version1234567890/frontend/Vendor/theme-example/nl_NL/jquery.js:3630:29)
    at mightThrow (https://www.example.com/static/version1234567890/frontend/Vendor/theme-example/nl_NL/jquery.js:3825:80)
    at process (https://www.example.com/static/version1234567890/frontend/Vendor/theme-example/nl_NL/jquery.js:3834:49)
    at https://www.example.com/static/version1234567890/frontend/Vendor/theme-example/nl_NL/jquery.js:3864:37
    at mightThrow (https://www.example.com/static/version1234567890/frontend/Vendor/theme-example/nl_NL/jquery.js:3766:60) undefined
jQuery.Deferred.exceptionHook @ jquery.js:4050
address-autofill-nl.js:171 Uncaught TypeError: Cannot read properties of undefined (reading 'setOptions')
    at UiClass.resetHouseNumberSelect (address-autofill-nl.js:171:42)
    at UiClass.onInputHouseNumber (address-autofill-nl.js:97:22)
    at setNested (objects.js:44:25)
    at Object.nested (objects.js:118:20)
    at UiClass.set (element.js:305:19)
    at updateValue (links.js:80:19)
    at setLink (links.js:209:17)
    at links.js:236:25
    at Registry._resolveRequest (registry.js:416:30)
    at Array.forEach (<anonymous>)
objects.js:116 Uncaught TypeError: path.split is not a function
    at Object.nested (objects.js:116:32)
    at UiClass.get (element.js:286:26)
    at UiClass.set (element.js:298:29)
    at updateValue (links.js:80:19)
    at setLink (links.js:209:17)
    at links.js:236:25
    at Registry._resolveRequest (registry.js:416:30)
    at Array.forEach (<anonymous>)
    at Registry._updateRequests (registry.js:398:18)
    at later (underscore.js:1153:47)
objects.js:116 Uncaught TypeError: path.split is not a function
    at Object.nested (objects.js:116:32)
    at UiClass.get (element.js:286:26)
    at UiClass.set (element.js:298:29)
    at updateValue (links.js:80:19)
    at setLink (links.js:209:17)
    at links.js:236:25
    at Registry._resolveRequest (registry.js:416:30)
    at Array.forEach (<anonymous>)
    at Registry._updateRequests (registry.js:398:18)
    at later (underscore.js:1153:47)
objects.js:116 Uncaught TypeError: path.split is not a function
    at Object.nested (objects.js:116:32)
    at UiClass.get (element.js:286:26)
    at UiClass.set (element.js:298:29)
    at updateValue (links.js:80:19)
    at setLink (links.js:209:17)
    at links.js:236:25
    at Registry._resolveRequest (registry.js:416:30)
    at Array.forEach (<anonymous>)
    at Registry._updateRequests (registry.js:398:18)
    at later (underscore.js:1153:47)
objects.js:116 Uncaught TypeError: path.split is not a function
    at Object.nested (objects.js:116:32)
    at UiClass.get (element.js:286:26)
    at UiClass.set (element.js:298:29)
    at updateValue (links.js:80:19)
    at setLink (links.js:209:17)
    at links.js:236:25
    at Registry._resolveRequest (registry.js:416:30)
    at Array.forEach (<anonymous>)
    at Registry._updateRequests (registry.js:398:18)
    at later (underscore.js:1153:47)
objects.js:116 Uncaught TypeError: path.split is not a function
    at Object.nested (objects.js:116:32)
    at UiClass.get (element.js:286:26)
    at UiClass.set (element.js:298:29)
    at updateValue (links.js:80:19)
    at setLink (links.js:209:17)
    at links.js:236:25
    at Registry._resolveRequest (registry.js:416:30)
    at Array.forEach (<anonymous>)
    at Registry._updateRequests (registry.js:398:18)
    at later (underscore.js:1153:47)
objects.js:116 Uncaught TypeError: path.split is not a function
    at Object.nested (objects.js:116:32)
    at UiClass.get (element.js:286:26)
    at UiClass.set (element.js:298:29)
    at updateValue (links.js:80:19)
    at setLink (links.js:209:17)
    at links.js:236:25
    at Registry._resolveRequest (registry.js:416:30)
    at Array.forEach (<anonymous>)
    at Registry._updateRequests (registry.js:398:18)
    at later (underscore.js:1153:47)
```

Somehow some properties are undefined, as also mentioned in several other issues: #77, #66.

In above log there seem to be two issues:
1. in `house-number-select.js`, when trying to read `'show_hide_address_fields'`, `this.settings` is undefined causing an exception.
2. in `address-autofill-nl.js`, `this.childHouseNumberSelect()` in `resetHouseNumberSelect` returns undefined, causing setOptions() to fail.

I have not found a reliable way to reproduce this yet.

**Comment by JerrySmidt** [comment]
I've added a [pull request](https://github.com/postcode-nl/PostcodeNl_Api_Magento2/pull/85) that may resolve this issue. If anyone here could verify if this PR works for you, please let me know.
